# Generated by Django 4.0.6 on 2022-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_category_is_most_viewed_category_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseauthor',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
