# Generated by Django 4.0.6 on 2022-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courseauthor_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
